### ISSUE TITLE
fix logout crash

### ISSUE THREAD

**Issue by modiaditya** [icebreaker-nexxus/Nexxus#55]

**Comment by modiaditya** [comment]
E/AndroidRuntime( 4736): android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
E/AndroidRuntime( 4736):     at android.app.ContextImpl.startActivity(ContextImpl.java:1050)
E/AndroidRuntime( 4736):     at android.app.ContextImpl.startActivity(ContextImpl.java:1037)
E/AndroidRuntime( 4736):     at android.content.ContextWrapper.startActivity(ContextWrapper.java:311)
E/AndroidRuntime( 4736):     at com.icebreakers.nexxus.utils.LogoutUtils.logout(LogoutUtils.java:19)
E/AndroidRuntime( 4736):     at com.icebreakers.nexxus.activities.EventListActivity.selectDrawerItem(EventListActivity.java:379)
E/AndroidRuntime( 4736):     at com.icebreakers.nexxus.activities.EventListActivity$6.onNavigationItemSelected(EventListActivity.java:363)
E/AndroidRuntime( 4736):     at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:156)
E/AndroidRuntime( 4736):     at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
E/AndroidRuntime( 4736):     at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
E/AndroidRuntime( 4736):     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
E/AndroidRuntime( 4736):     at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:342)
E/AndroidRuntime( 4736):     at android.view.View.performClick(View.java:4438)
E/AndroidRuntime( 4736):     at android.view.View$PerformClick.run(View.java:18422)
E/AndroidRuntime( 4736):     at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 4736):     at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4736):     at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 4736):     at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 4736):     at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 4736):     at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 4736):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 4736):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 4736):     at dalvik.system.NativeStart.main(Native Method)
W/genymotion_audio(  289): out_write() limiting sleep time 1846485022 to 39909
